name: Mirror AOM Repository

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: self-hosted

    steps:
      - name: Setup git
        run: |
          git config --global http.postBuffer 524288000
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
      
      - name: Clone or update source repository
        run: |
          if [ -d "source-repo" ]; then
            cd source-repo
            git fetch --all --prune
          else
            git clone --bare https://aomedia.googlesource.com/aom source-repo
            cd source-repo
          fi

      - name: Mirror repository to GitHub
        run: |
          cd source-repo
          git push --mirror https://github.com/SoftCreatR/aom.git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
