name: Mirror AOM Repository

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: self-hosted

    steps:
      - name: Setup git
        run: |
          git config --global core.compression 0
          git config --global http.postBuffer 1048576000
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone or update source repository
        run: |
          if [ -d "source-repo" ]; then
            cd source-repo
            git remote update --prune
          else
            git clone --mirror https://aomedia.googlesource.com/aom source-repo
            cd source-repo
          fi

      - name: Mirror repository to GitHub
        run: |
          cd source-repo
          git remote set-url --push origin https://${{ secrets.PAT_TOKEN }}@github.com/SoftCreatR/aom.git
          git push --mirror
